import type { AnalysisDefinition } from "../types";

export const analyses: AnalysisDefinition[] = [
  {
    id: "describe",
    name: "Descriptive map",
    family: "Explore",
    description: "Inspect distributions, missingness, centre, spread, and unusual observations.",
    question: "What does this dataset contain?",
    requires: ["One or more variables"],
    rPackage: "base",
    rFunction: "summary",
  },
  {
    id: "correlation",
    name: "Correlation",
    family: "Relationships",
    description: "Estimate the strength and direction of association between continuous variables.",
    question: "Do two measurements move together?",
    requires: ["Two continuous variables"],
    rPackage: "stats",
    rFunction: "cor.test",
  },
  {
    id: "t-test",
    name: "Independent samples t-test",
    family: "Group comparisons",
    description: "Compare the mean of a continuous outcome across two independent groups.",
    question: "Do two groups differ on a continuous outcome?",
    requires: ["One continuous outcome", "One two-level group"],
    rPackage: "stats",
    rFunction: "t.test",
  },
  {
    id: "anova",
    name: "One-way ANOVA",
    family: "Group comparisons",
    description: "Compare a continuous outcome across three or more independent groups.",
    question: "Does an outcome vary across several groups?",
    requires: ["One continuous outcome", "One categorical factor"],
    rPackage: "stats",
    rFunction: "aov",
  },
  {
    id: "regression",
    name: "Linear regression",
    family: "Models",
    description: "Model a continuous outcome from one or more predictors with inspectable assumptions.",
    question: "Which variables explain or predict a continuous outcome?",
    requires: ["One continuous outcome", "One or more predictors"],
    rPackage: "stats",
    rFunction: "lm",
  },
];
